AWSTemplateFormatVersion: 2010-09-09

Description: Deploys Amazon Keyspace and Table (for Apache Cassandra) - Drilling IOT Application

Parameters:
  OrgName:
    Type: String
    Default: org
    
  ProjectName:
    Type: String
    Default: iot
    
  Environment:
    Type: String
    Default: prod
    
  RegionName:
    Type: String
    Default: us-east-1
    
  KeyspaceName:
    Type: String
    Default: timeseries
  
  KeyspaceTableNameOne:
    Type: String
    Default: drilling
    
  KeyspaceNameTagKey:
    Type: String
    Default: Name
    
  KeyspaceTableNameTagKey:
    Type: String
    Default: Name
  
  KeyspaceCreatorTagKey:
    Type: String
    Default: Creator
    
  KeyspaceCreatorTagValue:
    Type: String
    Default: creator@domain.com
    
  KeyspaceTableBillingMode:
    Description: ON_DEMAND or PROVISIONED. For PROVISIONED, read & write capacity units must be specified. If ON_DEMAND is specified, capacity units are neglected.
    Type: String
    Default: ON_DEMAND
    
  KeyspaceTableBillingModeReadCapacityUnits:
    Type: String
    Default: 1
    
  KeyspaceTableBillingModeWriteCapacityUnits:
    Type: String
    Default: 1
    
  KeyspaceTablePointInTimeRecoveryEnabled:
    Type: String
    Default: false
    
Resources:
  OrgKeyspace:
    Type: AWS::Cassandra::Keyspace
    Properties:
      KeyspaceName: !Sub ${KeyspaceName}
      Tags:
        - Key: !Sub ${KeyspaceNameTagKey}
          Value: !Sub ${OrgName}-${ProjectName}-${Environment}-${RegionName}-${KeyspaceName}
        - Key: !Sub ${KeyspaceCreatorTagKey}
          Value: !Sub ${KeyspaceCreatorTagValue}
 
  OrgTableOne:
    DependsOn:
    - OrgKeyspace
    Type: AWS::Cassandra::Table
    Properties:
      KeyspaceName: !Sub ${KeyspaceName}
      TableName: !Sub ${KeyspaceTableNameOne}
      PartitionKeyColumns:
      - ColumnName: date_utc
        ColumnType: DATE
      ClusteringKeyColumns:
      - Column:
          ColumnName: id
          ColumnType: TIMEUUID
        OrderBy: DESC
      RegularColumns:
      # time (utc)
      - ColumnName: time_utc
        ColumnType: TIMESTAMP
      # drill string data from regular drilling operation (drill string-related)
      - ColumnName: ROP_fph
        ColumnType: DECIMAL
      - ColumnName: RPM_rpm
        ColumnType: DECIMAL
      - ColumnName: SPP_psi
        ColumnType: DECIMAL
      - ColumnName: DWOB_lb
        ColumnType: DECIMAL
      - ColumnName: SWOB_lb
        ColumnType: DECIMAL
      - ColumnName: TQR_Ibft
        ColumnType: DECIMAL
      - ColumnName: BHA_TYPE
        ColumnType: TEXT
      # mud data from regular drilling operation (mud-related)
      - ColumnName: MUD_WEIGHT_sg
        ColumnType: DECIMAL
      - ColumnName: MUD_PLASTIC_VISC_cp
        ColumnType: DECIMAL
      - ColumnName: MUD_YIELD_POINT_lb_per_100ft_sq
        ColumnType: DECIMAL
      - ColumnName: MUD_FLOW_RATE_gpm
        ColumnType: DECIMAL
      # mwd/lwd data (measured or calculated) from downhole MWD/LWD tool measurements
      - ColumnName: TVD_ft
        ColumnType: DECIMAL
      - ColumnName: MD_ft
        ColumnType: DECIMAL
      - ColumnName: INC_deg
        ColumnType: DECIMAL
      - ColumnName: AZIM_deg
        ColumnType: DECIMAL
      - ColumnName: Dogleg_deg_per_100ft
        ColumnType: DECIMAL
      - ColumnName: CALIPER_HOLE_SIZE_inches
        ColumnType: DECIMAL
      - ColumnName: GR_api
        ColumnType: DECIMAL
      - ColumnName: DEEP_RESISTIVITY_ohm_m
        ColumnType: DECIMAL
      - ColumnName: SHOCK_g
        ColumnType: DECIMAL
      # event data from MWD/LWD tool measurements and other sources
      - ColumnName: IS_VIBRATION
        ColumnType: BOOLEAN
      - ColumnName: IS_KICK
        ColumnType: BOOLEAN
      - ColumnName: IS_STUCKPIPE
        ColumnType: BOOLEAN
      BillingMode:
        Mode: !Sub ${KeyspaceTableBillingMode}
        ProvisionedThroughput:
          ReadCapacityUnits: !Sub ${KeyspaceTableBillingModeReadCapacityUnits}
          WriteCapacityUnits: !Sub ${KeyspaceTableBillingModeWriteCapacityUnits}
      PointInTimeRecoveryEnabled: !Sub ${KeyspaceTablePointInTimeRecoveryEnabled}
      Tags:
        - Key: !Sub ${KeyspaceTableNameTagKey}
          Value: !Sub ${OrgName}-${ProjectName}-${Environment}-${RegionName}-${KeyspaceTableNameOne}
        - Key: !Sub ${KeyspaceCreatorTagKey}
          Value: !Sub ${KeyspaceCreatorTagValue}
          
Outputs:
  OrgKeyspaceOutput:
    Description: Keyspace for grouping Tables.
    Value: !Ref OrgKeyspace
    Export:
      Name: !Sub ${OrgName}-${ProjectName}-${Environment}-${RegionName}-${KeyspaceName}
      
  OrgTableOneOutput:
    Description: Table for storing driling data.
    Value: !Ref OrgTableOne
    Export:
      Name: !Sub ${OrgName}-${ProjectName}-${Environment}-${RegionName}-${KeyspaceTableNameOne}
